//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiseTicket.Models
{
    using RaiseTicket.Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket
    {
        private DateTime _ReceivedDate = DateTime.Now;

        public DateTime Received
        {
            get
            {
                return _ReceivedDate;
            }
            set
            {
                _ReceivedDate = value;
            }
        }

        public int TicketId { get; set; }
        //[Display(Name = "Name", ResourceType = typeof(GlobalRes))]
        [Required(ErrorMessageResourceType = typeof(CreateTicket), ErrorMessageResourceName = "SelectProject")]
        public int ProjectId { get; set; }
        [Required(ErrorMessageResourceType = typeof(CreateTicket), ErrorMessageResourceName = "SelectDept")]
        public int DeptId { get; set; }        
        [Required(ErrorMessageResourceType = typeof(CreateTicket), ErrorMessageResourceName = "SelectEmployee")]
        public int EmpIoyeeId { get; set; }
        [Required(ErrorMessageResourceType = typeof(CreateTicket), ErrorMessageResourceName = "DescriptionRequired")]        
        public string Description { get; set; }
        //public System.DateTime Received { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
    }
}
